[API]
# Canvas API URL
API_URL = "https://oc.sjtu.edu.cn"
# Canvas API 访问令牌, 在Canvas设置中获取
API_KEY = "PASTE YOUR API_KEY HERE"

[COURSE_FOLDER]
# 课程文件夹名将通过此模板字符串生成
# 以下关键词可以放在大括号{}内
# CANVAS_ID : Canvas课程ID，如：10001
# SJTU_ID : 课号，如：CS101
# SEMESTER_ID : 学期号，如：2019-2020-2
# CLASSROOM_ID : 课程教学班序号，如：1
# NAME : 课程名，如：程序设计
# COURSE_CODE: 课程号
# 如果您的 Canvas URL 不是 oc.sjtu.edu.cn，那么您只能使用
# "COURSE_CODE" 和 "NAME"
# Example: "{CANVAS_ID}-({SEMESTER_ID})-{SJTU_ID}-{CLASSROOM_ID}-{NAME}"
# Example: "{SJTU_ID}-{NAME}" 将得到 "CS101-程序设计"
# Example: "{NAME}-{CLASSROOM_ID}" 可用于区分两个相同课程
# Example: "{SJTU_ID}-{NAME}/Canvas" 文件夹将创建在"10001-程序设计"下的"Canvas"子文件夹中
NAME_TEMPLATE = "{NAME}"
# 用此内容替换课程名中的非法字符
REPLACE_ILLEGAL_CHAR_WITH = "-"
# 忽略特定课程ID
IGNORED_CANVAS_ID = [10001, 10002, 10003]
# 单元文件夹命名模版
MODULE_FOLDER_TEMPLATE = "{IDX} {NAME}"
# 单元文件夹 "IDX" 的初值
MODULE_FOLDER_IDX_BEGIN_WITH = 0
# 合并单元名中的空格
# 比如："Module 1      Introduction"
# 会被合并成 "Module 1 Introduction"
CONSOLIDATE_MODULE_SPACE = false

# 为特定课程自定义文件夹名
[[COURSE_FOLDER.CUSTOM_NAME]]
CANVAS_ID = 10001
FOLDER_NAME = "高数/Canvas资料"
[[COURSE_FOLDER.CUSTOM_NAME]]
CANVAS_ID = 10002
FOLDER_NAME = "线性代数"

# 覆盖全局设置，为一门课程指定下载模式
[[COURSE_FOLDER.ORGANIZE_BY]]
CANVAS_ID = 10002
ORGANIZE_BY = "module"

[CHECKPOINT]
# 检查点文件路径(绝对路径或相对路径)，例如"files/.checkpoint"
CHECKPOINT_FILE = ".checkpoint"

[SYNC]
# 用于同步的目录路径(绝对路径或相对路径)
BASE_DIR = "files"
# 允许同步的最大单文件大小（以兆字节为单位），超过此大小的文件
# 将被忽略
MAX_SINGLE_FILE_SIZE = 100
# 允许同步的文件扩展名
ALLOW_FILE_EXTENSION_GROUP = ["DOCUMENT", "CUSTOM"]
ALLOW_FILE_EXTENSION = [".ppt", ".pptx", ".csv"]
# 同时同步文件创建日期和修改日期
OVERRIDE_FILE_TIME = true
# 是否显示详细的下载信息
VERBOSE = false
# 是否开启视频下载功能
ENABLE_VIDEO = false
# ffmpeg 可执行文件路径
# 若 ffmpeg 在您的环境变量 PATH 中，填写 "ffmpeg" 即可。
# 如果不是这样，请在运行 canvas_grab 之前设置好这个选项。
# 这里既可以使用相对路径，也可以使用绝对路径。
# 比如：ffmpeg 在 "canvas_grab_folder/bin/ffmpeg" 里
# "./bin/ffmpeg" (*nix) 或者 "bin/ffmpeg.exe" (Windows)
# 比如：ffmpeg 在一个绝对路径里
# "/usr/local/bin/ffmpeg" (*nix) 或 "C:/bin/ffmpeg.exe" (Windows)
# 路径中请勿出现空格或特殊字符
FFMPEG_PATH = "ffmpeg"
# 默认文件夹下载模式。可以是 "file" (按照“文件”结构下载) 或者 "module" (按照“单元”下载)。
# 如果默认方式不行的话，程序会自动尝试另一种。
ORGANIZE_BY = "file"
# 只下载本地不存在的文件，不覆盖任何已有文件，但会给出通知
NEVER_OVERWRITE_FILE = false
# 只下载未下载过的文件，被转移或更名的文件不会被重新下载
NEVER_DOWNLOAD_AGAIN = false

[EXTENSION]
# 自定义扩展名组，可填写在ALLOW_FILE_EXTENSION_GROUP中
VIDEO = [".mp4", ".avi", ".mkv"]
AUDIO = [".mp3", ".wav", ".aac", ".flac"]
IMAGE = [".bmp", ".jpg", ".jpeg", ".png", ".gif"]
DOCUMENT = [".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx", ".pdf", ".epub", ".caj"]
MYGROUP = [".rar", ".zip"]
ALLFORMAT = [""]