[API]
# Canvas API URL
API_URL = "https://oc.sjtu.edu.cn"
# Canvas API key, acquire it in Canvas Settings
API_KEY = "PASTE YOUR API_KEY HERE"

[COURSE]
# Only enable this option when you have two courses of the same name
USE_COURSE_ID = false

[CHECKPOINT]
# Checkpoint file path relative to current working directory
CHECKPOINT_FILE = ".checkpoint"

[SYNC]
# Directory path relative to current working directory for syncing
BASE_DIR = "files"
# Max single file size(in megabytes) for syncing, files bigger than 
# this will be ignored
MAX_SINGLE_FILE_SIZE = 100
# Only file extensions list below will be synced
ALLOW_FILE_EXTENSION_GROUP = ["DOCUMENT", "CUSTOM"]
ALLOW_FILE_EXTENSION = [".ppt", ".pptx", ".csv"]

[EXTENSION]
# All the groups below can be in ALLOW_FILE_EXTENSION_GROUP
VIDEO = [".mp4", ".avi", ".mkv"]
AUDIO = [".mp3", ".wav", ".aac", ".flac"]
IMAGE = [".bmp", ".jpg", ".jpeg", ".png", ".gif"]
DOCUMENT = [".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx", ".pdf", ".epub", ".caj"]
MYGROUP = [".rar", ".zip"]
ALLFORMAT = [""]