[API]
# Canvas API URL
API_URL = "https://oc.sjtu.edu.cn"
# Canvas API key, acquire it in Canvas Settings
API_KEY = "PASTE YOUR API_KEY HERE"

[COURSE_FOLDER]
# Course folder name will be formatted using the template
# only the keywords listed below are allowed in curly braces
# CANVAS_ID : id in Canvas, LIKE 10001
# SJTU_ID : id in Canvas, LIKE CS101
# SEMESTER_ID : LIKE 2019-2020-2
# CLASSROOM_ID : id used to distinguish two same courses
# NAME : course name
# Example: "{CANVAS_ID}.resource-({SEMESTER_ID})-{SJTU_ID}-{CLASSROOM_ID}-{NAME}"
NAME_TEMPLATE = "{SJTU_ID}-{NAME}"
# Some courses include illegal chars in its name, replace it
REPLACE_ILLEGAL_CHAR_WITH = "-"
# Ignore course

[CHECKPOINT]
# Checkpoint file path(relative or absolute)
CHECKPOINT_FILE = "files/.checkpoint"

[SYNC]
# Directory path(relative or absolute) for syncing
BASE_DIR = "files"
# Max single file size(in megabytes) for syncing, files bigger than 
# this will be ignored
MAX_SINGLE_FILE_SIZE = 100
# Only file extensions list below will be synced
ALLOW_FILE_EXTENSION_GROUP = ["DOCUMENT", "CUSTOM"]
ALLOW_FILE_EXTENSION = [".ppt", ".pptx", ".csv"]
# Override the access and modified times of the file
OVERRIDE_FILE_TIME = true

[EXTENSION]
# All the groups below can be in ALLOW_FILE_EXTENSION_GROUP
VIDEO = [".mp4", ".avi", ".mkv"]
AUDIO = [".mp3", ".wav", ".aac", ".flac"]
IMAGE = [".bmp", ".jpg", ".jpeg", ".png", ".gif"]
DOCUMENT = [".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx", ".pdf", ".epub", ".caj"]
MYGROUP = [".rar", ".zip"]
ALLFORMAT = [""]