[API]
# Canvas API URL
API_URL = "https://oc.sjtu.edu.cn"
# Canvas API key, acquire it in Canvas Settings
API_KEY = "PASTE YOUR API_KEY HERE"

[COURSE_FOLDER]
# Course folder name will be formatted using the template
# only the keywords listed below are allowed in curly braces
# CANVAS_ID : id in Canvas, LIKE 10001
# SJTU_ID : id in SJTU, LIKE CS101
# SEMESTER_ID : LIKE 2019-2020-2
# CLASSROOM_ID : id used to distinguish two same courses
# NAME : course name
# COURSE_CODE: course code on canvas
# If your canvas endpoint is not "oc.sjtu.edu.cn", then you can only use
# "COURSE_CODE" and "NAME"
# Example: "{CANVAS_ID}.resource-({SEMESTER_ID})-{SJTU_ID}-{CLASSROOM_ID}-{NAME}"
# Example: "{SJTU_ID}-{NAME}" if you want "CS100-Course"
# Example: "{NAME}({CLASSROOM_ID})" if you have two courses of same name
# Example: "{SJTU_ID}-{NAME}/Canvas" if you want to download in a subfolder "Canvas"
NAME_TEMPLATE = "{NAME}"
# Some courses include illegal chars in its name, replace it
REPLACE_ILLEGAL_CHAR_WITH = "-"
# Ignore courses
IGNORED_CANVAS_ID = [10001, 10002, 10003]
# Module folder name template
MODULE_FOLDER_TEMPLATE = "{IDX} {NAME}"
# Module folder IDX start number
MODULE_FOLDER_IDX_BEGIN_WITH = 0
# Consolidate space in module name
# For example: "Module 1      Introduction"
# will be consolidated to "Module 1 Introduction"
# if this option is set to true
CONSOLIDATE_MODULE_SPACE = false

# Customize the folder name for course
[[COURSE_FOLDER.CUSTOM_NAME]]
CANVAS_ID = 10001
FOLDER_NAME = "Calculus/resource"
[[COURSE_FOLDER.CUSTOM_NAME]]
CANVAS_ID = 10002
FOLDER_NAME = "Linear Algebra"

# Override organization mode
[[COURSE_FOLDER.ORGANIZE_BY]]
CANVAS_ID = 10002
ORGANIZE_BY = "module"

[CHECKPOINT]
# Checkpoint file path(relative or absolute), e.g. 'files/.checkpoint'
CHECKPOINT_FILE = ".checkpoint"

[SYNC]
# Directory path(relative or absolute) for syncing
BASE_DIR = "files"
# Max single file size(in megabytes) for syncing, files bigger than 
# this will be ignored
MAX_SINGLE_FILE_SIZE = 100
# Only file extensions list below will be synced
ALLOW_FILE_EXTENSION_GROUP = ["DOCUMENT", "CUSTOM"]
ALLOW_FILE_EXTENSION = [".ppt", ".pptx", ".csv"]
# Override the created and modified times of the file
OVERRIDE_FILE_TIME = true
# Show verbose information
VERBOSE = false
# Enable video download from v.sjtu.edu.cn
ENABLE_VIDEO = false
# ffmpeg binary path
# If ffmpeg is inside your PATH, just use "ffmpeg"
# If not, specify ffmpeg binary before running canvas_grab
# You may set this value to relative path to canvas_grab binary
# e.g. ffmpeg binary is located at "canvas_grab_folder/bin/ffmpeg"
# "./bin/ffmpeg" (*nix) or "bin/ffmpeg" (Windows)
# e.g. ffmpeg binary is located at some absolute path
# "/usr/local/bin/ffmpeg" (*nix) or "C:/bin/ffmpeg" (Windows)
# Don't include special characters and space in this path
FFMPEG_PATH = "ffmpeg"
# Default organize mode, "file" or "module" or "module_with_file".
# If "file" or "module" organize mode fails, it will fallback to another.
# "module_with_file" will first download files in module, then download
# those in files but not in modules in "unmoduled" folder
ORGANIZE_BY = "file"
# Never overwrite any existing file. There will be a message.
NEVER_OVERWRITE_FILE = false
# If a file has been downloaded in canvas_grab before, 
# it won't be downloaded even after it is moved or renamed.
NEVER_DOWNLOAD_AGAIN = false
# Scan stale file (those created by yourself and not on Canvas)
SCAN_STALE_FILE = false
# Allow auto check new version
ALLOW_VERSION_CHECK = true

[EXTENSION]
# All the groups below can be in ALLOW_FILE_EXTENSION_GROUP
VIDEO = [".mp4", ".avi", ".mkv"]
AUDIO = [".mp3", ".wav", ".aac", ".flac"]
IMAGE = [".bmp", ".jpg", ".jpeg", ".png", ".gif"]
DOCUMENT = [".ppt", ".pptx", ".doc", ".docx", ".xls", ".xlsx", ".pdf", ".epub", ".caj"]
MYGROUP = [".rar", ".zip"]
ALLFORMAT = [""]